apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: almafa
  description: The place to be, for great artists asdasd asd as dasd asd asfsdfagfdgfdg sdf gdsfg dfsh fdhdfshg fsd hsdfh dfsh dfs 
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
