apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-gitlab2
  description: The place to be, for great artists
  labels:
    example.com/custom: custom_label_value
  annotations:
         gitlab.com/project-id: "168033"
  tags:
    - gitlab
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
  system: public-websites
